version: '3'

services:
  tutorial-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./llm_cache.json:/app/llm_cache.json
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - LOG_DIR=/app/logs
      - CACHE_FILE=/app/llm_cache.json
      - CACHE_ENABLED=true
    restart: unless-stopped