version: '3'

services:
  tutorial-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./llm_cache.json:/app/llm_cache.json
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - LOG_DIR=/app/logs
      - CACHE_FILE=/app/llm_cache.json
      - CACHE_ENABLED=true
      - OUTPUT_DIR=/app/output
    restart: unless-stopped
    # Ensure the container has write permissions to the output directory
    user: "${UID:-1000}:${GID:-1000}"
    # Create output directory with proper permissions
    command: >
      bash -c "
        mkdir -p /app/output &&
        chmod -R 777 /app/output &&
        mkdir -p /app/logs &&
        chmod -R 777 /app/logs &&
        touch /app/llm_cache.json &&
        chmod 666 /app/llm_cache.json &&
        streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "